version: '3'
services:
  app:
    image: yrysdaulet/goang-app-assignment-3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assignment-3
      DB_HOST: localhost
      DB_PORT: 5432
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assignment-3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: null


#  app:
#    image: yrysdaulet/mygolang-app-assigment-3
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: assignment-3
#      DB_HOST: localhost
#      DB_PORT: 5432
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/app
#    depends_on:
